export const ProgrammingContest = {
  id: "MENU_EDUCATION_TEACHING_MANAGEMENT_TEACHER",
  path: "",
  isPublic: false,
  icon: "LocalLibraryIcon",
  text: "Programming Contest",
  child: [
    {
      id: "MENU_EDUCATION_TEACHING_MANAGEMENT_TEACHER_VIEW_LIST_COURSE",
      path: "/programming-contest/list-problems",
      isPublic: false,
      icon: null,
      text: "Problem",
      child: [],
    },
    {
      id: "MENU_EDUCATION_TEACHING_MANAGEMENT_TEACHER_VIEW_LIST_COURSE",
      path: "/programming-contest/create-problem",
      isPublic: false,
      icon: null,
      text: "Create Problem",
      child: [],
    },
    {
      id: "MENU_EDUCATION_TEACHING_MANAGEMENT_TEACHER_VIEW_LIST_COURSE",
      path: "/programming-contest/create-contest",
      isPublic: false,
      icon: null,
      text: "Create Contest",
      child: [],
    },
    {
      id: "MENU_EDUCATION_TEACHING_MANAGEMENT_TEACHER_VIEW_LIST_COURSE",
      path: "/programming-contest/list-contest",
      isPublic: false,
      icon: null,
      text: "List Contest",
      child: [],
    },
    {
      id: "MENU_EDUCATION_LEARNING_MANAGEMENT_STUDENT_REGISTER_CLASS",
      path: "/programming-contest/ide",
      isPublic: false,
      icon: null,
      text: "IDE",
      child: [],
    },
  ],
};
