version: '3'
services:
  leetcode-be:
    container_name: leetcode-be
    build:
      context: .
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - docker-service
      - redis
      - postgres
    environment:
      - DOCKER_SERVER_HOST=http://leetcode-docker-service:2375
      - SQL_DB_HOST=leetcode-postgres
      - REDIS_HOST=leetcode-redis

  postgres:
    container_name: leetcode-postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=leetcode
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

  redis:
    container_name: leetcode-redis
    image: redis:latest

  docker-service:
    hostname: docker-service
    container_name: leetcode-docker-service
    image: docker:dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=

  leetcode-fe:
    container_name: leetcode-fe
    build:
      context: ./FrontEnd/mini-leetcode-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - REACT_APP_BACKEND_URL=http://172.17.0.1:8080/api


